name: Build
on:
  pull_request:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Tool Dependencies
        uses: jdx/mise-action/@v2

      - name: Lib Dependencies
        run: pip install python3-protobuf

      - name: Build JS
        run: |
          bin/build-js
          bin/build-arduino

      - uses: actions/upload-artifact@v4
        with:
            name: javascript-wrapper
            path: ./js_out
