name: Build
on:
  pull_request:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Tool Dependencies
        uses: jdx/mise-action/@v2

      - name: Lib Dependencies
        run: pip install python3-protobuf

      - run: |
          which python
          which pip
          which protoc
          which protoc-gen-js
          which protolint

      - name: Build JS
        run: bin/build-js

      - name: Build Arduino
        run: bin/build-arduino

      - uses: actions/upload-artifact@v4
        with:
            name: javascript-wrapper
            path: ./js_out
